In [1]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 모델의 최적의 하이퍼 파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

from tqdm import tqdm
import pandas as pd
import time


# 학습 모델 저장을 위한 라이브러리
import pickle

In [2]:
# 데이터를 읽어온다.
df1 = pd.read_csv('/Users/hapresent/Desktop/11_파이널프로젝트관련/open/train/7.마케팅정보/07_마케팅정보_train_selected.csv')
df2 = pd.read_csv('/Users/hapresent/Desktop/11_파이널프로젝트관련/open/train/8.성과정보/08_성과정보_train_selected.csv')

In [3]:
df1

,ID,기준년월,컨택건수_채권_R6M,컨택건수_부대서비스_TM_R6M,캠페인접촉건수_R12M,컨택건수_보험_TM_B0M,컨택건수_카드론_TM_B0M,컨택건수_카드론_LMS_B0M,컨택건수_카드론_TM_R6M,컨택건수_CA_EM_B0M,컨택건수_CA_LMS_R6M,컨택건수_리볼빙_LMS_B0M,컨택건수_이용유도_EM_B0M,컨택건수_이용유도_청구서_B0M,컨택건수_이용유도_LMS_B0M,Segment
0,TRAIN_000000,201807,0,0,1회 이상,0,0,0,0,0,0,0,13,0,2,D
1,TRAIN_000001,201807,0,0,15회 이상,0,3,0,9,0,2,0,0,0,0,E
2,TRAIN_000002,201807,0,0,1회 이상,0,0,0,0,0,0,0,0,0,0,C
3,TRAIN_000003,201807,0,0,1회 이상,0,0,0,0,0,0,0,13,1,2,D
4,TRAIN_000004,201807,0,0,1회 이상,0,0,0,0,0,2,0,0,1,3,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,TRAIN_399995,201812,0,0,1회 이상,0,0,0,0,0,0,0,0,0,0,E
2399996,TRAIN_399996,201812,0,0,20회 이상,0,0,0,9,0,0,0,13,0,2,D
2399997,TRAIN_399997,201812,0,0,1회 이상,0,0,0,0,0,0,0,0,1,0,C
2399998,TRAIN_399998,201812,0,0,1회 이상,0,0,0,0,0,0,0,0,0,0,E
2399999,TRAIN_399999,201812,0,0,1회 이상,0,0,0,0,0,0,0,0,0,0,E

In [4]:
df2

,ID,기준년월,증감율_이용건수_할부_전월,증감율_이용건수_CA_분기,증감율_이용건수_체크_분기,증감율_이용금액_할부_전월,증감율_이용금액_일시불_전월,잔액_신판ca최대한도소진율_r6m,변동률_RV일시불평잔,변동률_잔액_B1M,변동률_잔액_일시불_B1M,혜택수혜율_R3M,Segment
0,TRAIN_000000,201807,1.999996,0.0,-1.999996,1.999996,0.313300,0.849842,0.999998,0.261886,0.270752,1.044401,D
1,TRAIN_000001,201807,0.000000,0.0,0.000000,0.000000,-1.010817,0.851009,1.092698,-0.563388,-0.670348,0.000000,E
2,TRAIN_000002,201807,-1.999996,0.0,0.000000,-1.999996,0.289565,0.938161,1.006124,-0.046516,0.058114,0.524159,C
3,TRAIN_000003,201807,-1.999996,0.0,0.000000,-0.138126,0.276947,1.135424,0.999998,0.023821,0.258943,0.880925,D
4,TRAIN_000004,201807,0.000000,0.0,-0.404712,0.000000,0.000028,0.000000,0.999998,0.000000,0.000000,NaN,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,TRAIN_399995,201812,0.000000,0.0,-0.105145,0.000000,0.000027,0.032439,0.999998,0.000000,0.000000,NaN,E
2399996,TRAIN_399996,201812,0.000000,0.0,0.000000,0.000000,0.207099,0.168081,0.999998,-0.203251,-0.159143,1.377071,D
2399997,TRAIN_399997,201812,0.000000,0.0,0.000000,-1.999996,0.229573,0.190393,0.999998,0.027319,0.126581,0.000000,C
2399998,TRAIN_399998,201812,0.000000,0.0,0.000000,0.000000,0.000034,0.012677,0.999998,0.000000,0.000000,NaN,E
2399999,TRAIN_399999,201812,0.000000,0.0,0.000000,-0.137569,0.284271,0.053036,0.999998,-0.039845,-0.002659,0.000000,E

In [5]:
# 만약 df1 기준으로 df2의 컬럼을 붙이고 싶다면
merged_df = pd.merge(df1, df2, on=['ID', '기준년월', 'Segment'], how='left')
merged_df

,ID,기준년월,컨택건수_채권_R6M,컨택건수_부대서비스_TM_R6M,캠페인접촉건수_R12M,컨택건수_보험_TM_B0M,컨택건수_카드론_TM_B0M,컨택건수_카드론_LMS_B0M,컨택건수_카드론_TM_R6M,컨택건수_CA_EM_B0M,...,증감율_이용건수_할부_전월,증감율_이용건수_CA_분기,증감율_이용건수_체크_분기,증감율_이용금액_할부_전월,증감율_이용금액_일시불_전월,잔액_신판ca최대한도소진율_r6m,변동률_RV일시불평잔,변동률_잔액_B1M,변동률_잔액_일시불_B1M,혜택수혜율_R3M
0,TRAIN_000000,201807,0,0,1회 이상,0,0,0,0,0,...,1.999996,0.0,-1.999996,1.999996,0.313300,0.849842,0.999998,0.261886,0.270752,1.044401
1,TRAIN_000001,201807,0,0,15회 이상,0,3,0,9,0,...,0.000000,0.0,0.000000,0.000000,-1.010817,0.851009,1.092698,-0.563388,-0.670348,0.000000
2,TRAIN_000002,201807,0,0,1회 이상,0,0,0,0,0,...,-1.999996,0.0,0.000000,-1.999996,0.289565,0.938161,1.006124,-0.046516,0.058114,0.524159
3,TRAIN_000003,201807,0,0,1회 이상,0,0,0,0,0,...,-1.999996,0.0,0.000000,-0.138126,0.276947,1.135424,0.999998,0.023821,0.258943,0.880925
4,TRAIN_000004,201807,0,0,1회 이상,0,0,0,0,0,...,0.000000,0.0,-0.404712,0.000000,0.000028,0.000000,0.999998,0.000000,0.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,TRAIN_399995,201812,0,0,1회 이상,0,0,0,0,0,...,0.000000,0.0,-0.105145,0.000000,0.000027,0.032439,0.999998,0.000000,0.000000,NaN
2399996,TRAIN_399996,201812,0,0,20회 이상,0,0,0,9,0,...,0.000000,0.0,0.000000,0.000000,0.207099,0.168081,0.999998,-0.203251,-0.159143,1.377071
2399997,TRAIN_399997,201812,0,0,1회 이상,0,0,0,0,0,...,0.000000,0.0,0.000000,-1.999996,0.229573,0.190393,0.999998,0.027319,0.126581,0.000000
2399998,TRAIN_399998,201812,0,0,1회 이상,0,0,0,0,0,...,0.000000,0.0,0.000000,0.000000,0.000034,0.012677,0.999998,0.000000,0.000000,NaN
2399999,TRAIN_399999,201812,0,0,1회 이상,0,0,0,0,0,...,0.000000,0.0,0.000000,-0.137569,0.284271,0.053036,0.999998,-0.039845,-0.002659,0.000000

In [6]:
merged_df.columns

Index(['ID', '기준년월', '컨택건수_채권_R6M', '컨택건수_부대서비스_TM_R6M', '캠페인접촉건수_R12M',
       '컨택건수_보험_TM_B0M', '컨택건수_카드론_TM_B0M', '컨택건수_카드론_LMS_B0M',
       '컨택건수_카드론_TM_R6M', '컨택건수_CA_EM_B0M', '컨택건수_CA_LMS_R6M',
       '컨택건수_리볼빙_LMS_B0M', '컨택건수_이용유도_EM_B0M', '컨택건수_이용유도_청구서_B0M',
       '컨택건수_이용유도_LMS_B0M', 'Segment', '증감율_이용건수_할부_전월', '증감율_이용건수_CA_분기',
       '증감율_이용건수_체크_분기', '증감율_이용금액_할부_전월', '증감율_이용금액_일시불_전월',
       '잔액_신판ca최대한도소진율_r6m', '변동률_RV일시불평잔', '변동률_잔액_B1M', '변동률_잔액_일시불_B1M',
       '혜택수혜율_R3M'],
      dtype='object')

In [7]:
# Segment를 제외한 컬럼 리스트
cols = [col for col in merged_df.columns if col != 'Segment']

# Segment를 맨 마지막에 붙이기
merged_df = merged_df[cols + ['Segment']]

In [8]:
merged_df

,ID,기준년월,컨택건수_채권_R6M,컨택건수_부대서비스_TM_R6M,캠페인접촉건수_R12M,컨택건수_보험_TM_B0M,컨택건수_카드론_TM_B0M,컨택건수_카드론_LMS_B0M,컨택건수_카드론_TM_R6M,컨택건수_CA_EM_B0M,...,증감율_이용건수_CA_분기,증감율_이용건수_체크_분기,증감율_이용금액_할부_전월,증감율_이용금액_일시불_전월,잔액_신판ca최대한도소진율_r6m,변동률_RV일시불평잔,변동률_잔액_B1M,변동률_잔액_일시불_B1M,혜택수혜율_R3M,Segment
0,TRAIN_000000,201807,0,0,1회 이상,0,0,0,0,0,...,0.0,-1.999996,1.999996,0.313300,0.849842,0.999998,0.261886,0.270752,1.044401,D
1,TRAIN_000001,201807,0,0,15회 이상,0,3,0,9,0,...,0.0,0.000000,0.000000,-1.010817,0.851009,1.092698,-0.563388,-0.670348,0.000000,E
2,TRAIN_000002,201807,0,0,1회 이상,0,0,0,0,0,...,0.0,0.000000,-1.999996,0.289565,0.938161,1.006124,-0.046516,0.058114,0.524159,C
3,TRAIN_000003,201807,0,0,1회 이상,0,0,0,0,0,...,0.0,0.000000,-0.138126,0.276947,1.135424,0.999998,0.023821,0.258943,0.880925,D
4,TRAIN_000004,201807,0,0,1회 이상,0,0,0,0,0,...,0.0,-0.404712,0.000000,0.000028,0.000000,0.999998,0.000000,0.000000,NaN,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,TRAIN_399995,201812,0,0,1회 이상,0,0,0,0,0,...,0.0,-0.105145,0.000000,0.000027,0.032439,0.999998,0.000000,0.000000,NaN,E
2399996,TRAIN_399996,201812,0,0,20회 이상,0,0,0,9,0,...,0.0,0.000000,0.000000,0.207099,0.168081,0.999998,-0.203251,-0.159143,1.377071,D
2399997,TRAIN_399997,201812,0,0,1회 이상,0,0,0,0,0,...,0.0,0.000000,-1.999996,0.229573,0.190393,0.999998,0.027319,0.126581,0.000000,C
2399998,TRAIN_399998,201812,0,0,1회 이상,0,0,0,0,0,...,0.0,0.000000,0.000000,0.000034,0.012677,0.999998,0.000000,0.000000,NaN,E
2399999,TRAIN_399999,201812,0,0,1회 이상,0,0,0,0,0,...,0.0,0.000000,-0.137569,0.284271,0.053036,0.999998,-0.039845,-0.002659,0.000000,E

In [9]:
train_df = merged_df

In [10]:
train_df.isnull().sum()

ID                         0
기준년월                       0
컨택건수_채권_R6M                0
컨택건수_부대서비스_TM_R6M          0
캠페인접촉건수_R12M               0
컨택건수_보험_TM_B0M             0
컨택건수_카드론_TM_B0M            0
컨택건수_카드론_LMS_B0M           0
컨택건수_카드론_TM_R6M            0
컨택건수_CA_EM_B0M             0
컨택건수_CA_LMS_R6M            0
컨택건수_리볼빙_LMS_B0M           0
컨택건수_이용유도_EM_B0M           0
컨택건수_이용유도_청구서_B0M          0
컨택건수_이용유도_LMS_B0M          0
증감율_이용건수_할부_전월             0
증감율_이용건수_CA_분기             0
증감율_이용건수_체크_분기             0
증감율_이용금액_할부_전월             0
증감율_이용금액_일시불_전월            0
잔액_신판ca최대한도소진율_r6m         0
변동률_RV일시불평잔                0
변동률_잔액_B1M                 0
변동률_잔액_일시불_B1M             0
혜택수혜율_R3M             488746
Segment                    0
dtype: int64

## 결측치 제거

In [12]:
train_df = train_df.dropna(subset=['혜택수혜율_R3M'])

# 랜덤포레스트 피처 중요도 확인

In [14]:
# from sklearn.ensemble import RandomForestClassifier

# # 모델 학습
# rf_model = RandomForestClassifier(random_state=42)
# rf_model.fit(train_X, train_y)

# # 피처 중요도 추출
# importances = rf_model.feature_importances_
# feature_names = train_X.columns

In [15]:
# import pandas as pd

# feature_importance_df = pd.DataFrame({
#     'Feature': feature_names,
#     'Importance': importances
# }).sort_values(by='Importance', ascending=False)

# # 피처 중요도 정렬 후 인덱스 초기화
# feature_importance_df = feature_importance_df.sort_values(by="Importance", ascending=False).reset_index(drop=True)
# feature_importance_df

# 상위 15개 컬럼만 추출하기

In [17]:
# 피처 중요도 정렬 후 인덱스 초기화
# feature_importance_df.head(15)

In [18]:
selected_cols = ['ID','기준년월','잔액_신판ca최대한도소진율_r6m', '증감율_이용금액_일시불_전월', '혜택수혜율_R3M'
                , '변동률_잔액_B1M' ,'변동률_잔액_일시불_B1M',
'증감율_이용건수_체크_분기' ,'변동률_RV일시불평잔'  ,'증감율_이용금액_할부_전월', '컨택건수_이용유도_EM_B0M',
                 '증감율_이용건수_CA_분기' ,'컨택건수_카드론_TM_R6M',
'증감율_이용건수_할부_전월' ,'캠페인접촉건수_R12M', 'Segment']

In [19]:
train_df = train_df[selected_cols]

In [20]:
train_df

,ID,기준년월,잔액_신판ca최대한도소진율_r6m,증감율_이용금액_일시불_전월,혜택수혜율_R3M,변동률_잔액_B1M,변동률_잔액_일시불_B1M,증감율_이용건수_체크_분기,변동률_RV일시불평잔,증감율_이용금액_할부_전월,컨택건수_이용유도_EM_B0M,증감율_이용건수_CA_분기,컨택건수_카드론_TM_R6M,증감율_이용건수_할부_전월,캠페인접촉건수_R12M,Segment
0,TRAIN_000000,201807,0.849842,0.313300,1.044401,0.261886,0.270752,-1.999996,0.999998,1.999996,13,0.0,0,1.999996,1회 이상,D
1,TRAIN_000001,201807,0.851009,-1.010817,0.000000,-0.563388,-0.670348,0.000000,1.092698,0.000000,0,0.0,9,0.000000,15회 이상,E
2,TRAIN_000002,201807,0.938161,0.289565,0.524159,-0.046516,0.058114,0.000000,1.006124,-1.999996,0,0.0,0,-1.999996,1회 이상,C
3,TRAIN_000003,201807,1.135424,0.276947,0.880925,0.023821,0.258943,0.000000,0.999998,-0.138126,13,0.0,0,-1.999996,1회 이상,D
6,TRAIN_000006,201807,0.470058,0.185161,0.000000,-0.224903,-0.183413,0.000000,1.054546,0.000000,0,0.0,0,0.000000,1회 이상,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399993,TRAIN_399993,201812,0.150702,0.224904,1.796138,0.056099,0.006694,0.000000,0.999998,0.000000,0,0.0,0,0.000000,1회 이상,C
2399994,TRAIN_399994,201812,0.064429,0.225859,0.000000,-0.042365,0.057020,0.000000,1.046146,0.000000,0,0.0,0,0.000000,1회 이상,E
2399996,TRAIN_399996,201812,0.168081,0.207099,1.377071,-0.203251,-0.159143,0.000000,0.999998,0.000000,13,0.0,9,0.000000,20회 이상,D
2399997,TRAIN_399997,201812,0.190393,0.229573,0.000000,0.027319,0.126581,0.000000,0.999998,-1.999996,0,0.0,0,0.000000,1회 이상,C
2399999,TRAIN_399999,201812,0.053036,0.284271,0.000000,-0.039845,-0.002659,0.000000,0.999998,-0.137569,0,0.0,0,0.000000,1회 이상,E

## 범주형 변수들에 대해 라벨인코딩 진행!

In [22]:
#LabelEncoder 학습
le_campaign = LabelEncoder() #1.캠페인접촉건수_R12M
le_segment = LabelEncoder() #2. Segment

# 2. fit
le_campaign.fit(train_df['캠페인접촉건수_R12M'])
le_segment.fit(train_df['Segment'])

# 3. transform
train_df['캠페인접촉건수_R12M'] = le_campaign.transform(train_df['캠페인접촉건수_R12M'])
train_df['Segment'] = le_segment.transform(train_df['Segment'])

In [23]:
# 입력과 결과로 나눈다.
X = train_df.drop(['ID','Segment'], axis=1)
y = train_df['Segment']

In [24]:
train_X = X
train_y = y

# 모델

In [26]:
# 학습이 완료된 모델을 저장할 파일 이름
best_model_path = 'model/best_model_marketing_performance.dat'
# 교차검증 횟수
cv_count = 5
# 교차 검증
kfold = KFold(n_splits=cv_count, shuffle=True, random_state=1)
# 평가 결과를 담을 리스트
# 필요하다면 다른 것도 만들어주세요
f1_score_list = []
# 학습 모델 이름
model_name_list = []

In [27]:
# KNN
knn_basic_model = KNeighborsClassifier()
# 교차 검증을 수행한다
r1 = cross_val_score(knn_basic_model, train_X, train_y, scoring='f1_micro', cv=kfold)
# 평가 결과를 담아준다.
f1_score_list.append(r1.mean())
# 학습 모델 이름을 담아준다.
model_name_list.append("KNN Basic")

In [28]:
# LogisticRegression
lr_basic_model = LogisticRegression()
# 교차 검증을 수행한다
r1 = cross_val_score(lr_basic_model, train_X, train_y, scoring='f1_micro', cv=kfold)
# 평가 결과를 담아준다.
f1_score_list.append(r1.mean())
# 학습 모델 이름을 담아준다.
model_name_list.append("LogisticRegression Basic")

In [29]:
# # SVC
# svc_basic_model = SVC(probability=True)
# # 교차 검증을 수행한다
# r1 = cross_val_score(svc_basic_model, train_X, train_y, scoring='f1_micro', cv=kfold)
# # 평가 결과를 담아준다.
# f1_score_list.append(r1.mean())
# # 학습 모델 이름을 담아준다.
# model_name_list.append("SVC Basic")

In [30]:
# # DecisionTree
# tree_basic_model = DecisionTreeClassifier()
# # 교차 검증을 수행한다
# r1 = cross_val_score(tree_basic_model, train_X, train_y, scoring='f1_micro', cv=kfold)
# # 평가 결과를 담아준다.
# f1_score_list.append(r1.mean())
# # 학습 모델 이름을 담아준다.
# model_name_list.append("DecisionTree Basic")

In [31]:
# RandomForest
rf_basic_model = RandomForestClassifier()
# 교차 검증을 수행한다
r1 = cross_val_score(rf_basic_model, train_X, train_y, scoring='f1_micro', cv=kfold)
# 평가 결과를 담아준다.
f1_score_list.append(r1.mean())
# 학습 모델 이름을 담아준다.
model_name_list.append("RandomForest Basic")

In [32]:
# # AdaBoost
# ada_basic_model = AdaBoostClassifier()
# # 교차 검증을 수행한다
# r1 = cross_val_score(ada_basic_model, train_X, train_y, scoring='f1_micro', cv=kfold)
# # 평가 결과를 담아준다.
# f1_score_list.append(r1.mean())
# # 학습 모델 이름을 담아준다.
# model_name_list.append("AdaBoost Basic")

In [33]:
d1 = {
    'f1 score' : f1_score_list
}
result_df = pd.DataFrame(d1, index=model_name_list)
result_df.sort_values(by='f1 score', ascending=False, inplace=True)
result_df

                          f1 score
RandomForest Basic        0.768794
LogisticRegression Basic  0.762064
KNN Basic                 0.729048

In [34]:
# LGBM
lgbm_basic_model = LGBMClassifier(verbose=-1)
# 교차 검증을 수행한다
r1 = cross_val_score(lgbm_basic_model, train_X, train_y, scoring='f1_micro', cv=kfold)
# 평가 결과를 담아준다.
f1_score_list.append(r1.mean())
# 학습 모델 이름을 담아준다.
model_name_list.append("LGBM Basic")

In [35]:
# XGBoost
xgboost_basic_model = XGBClassifier(verbose=-1, silent=True)
# 교차 검증을 수행한다
r1 = cross_val_score(xgboost_basic_model, train_X, train_y, scoring='f1_micro', cv=kfold)
# 평가 결과를 담아준다.
f1_score_list.append(r1.mean())
# 학습 모델 이름을 담아준다.
model_name_list.append("XGBoost Basic")

In [ ]:
# HardVoting 구성
temp_model1 = KNeighborsClassifier()
temp_model2 = LogisticRegression()
# temp_model3 = SVC(probability=True)
temp_model4 = DecisionTreeClassifier()
temp_model5 = RandomForestClassifier()
temp_model6 = AdaBoostClassifier()
# temp_model7 = GradientBoostingClassifier()
temp_model8 = LGBMClassifier(verbose=-1)
temp_model9 = XGBClassifier(verbose=-1, silent=True)

hard_voting_model_list = [
    ('model1', temp_model1),
    ('model2', temp_model2),
    # ('model3', temp_model3),
    ('model4', temp_model4),
    ('model5', temp_model5),
    ('model6', temp_model6),
    # ('model7', temp_model7),
    ('model8', temp_model8),
    ('model9', temp_model9),
]

hard_voting_basic_model = VotingClassifier(estimators=hard_voting_model_list, voting='hard')

# 교차 검증을 수행한다
r1 = cross_val_score(hard_voting_basic_model, train_X, train_y, scoring='f1', cv=kfold)
# 평가 결과를 담아준다.
f1_score_list.append(r1.mean())
# 학습 모델 이름을 담아준다.
model_name_list.append("HardVoting Basic")

In [ ]:
# SoftVoting 구성
temp_model1 = KNeighborsClassifier()
temp_model2 = LogisticRegression()
# temp_model3 = SVC(probability=True)
temp_model4 = DecisionTreeClassifier()
temp_model5 = RandomForestClassifier()
temp_model6 = AdaBoostClassifier()
# temp_model7 = GradientBoostingClassifier()
temp_model8 = LGBMClassifier(verbose=-1)
temp_model9 = XGBClassifier(verbose=-1, silent=True)

soft_voting_model_list = [
    ('model1', temp_model1),
    ('model2', temp_model2),
    # ('model3', temp_model3),
    ('model4', temp_model4),
    ('model5', temp_model5),
    ('model6', temp_model6),
    # ('model7', temp_model7),
    ('model8', temp_model8),
    ('model9', temp_model9),
]

soft_voting_basic_model = VotingClassifier(estimators=soft_voting_model_list, voting='soft')

# 교차 검증을 수행한다
r1 = cross_val_score(soft_voting_basic_model, train_X, train_y, scoring='f1', cv=kfold)
# 평가 결과를 담아준다.
f1_score_list.append(r1.mean())
# 학습 모델 이름을 담아준다.
model_name_list.append("SoftVoting Basic")

In [ ]:
d1 = {
    'f1 score' : f1_score_list
}
result_df = pd.DataFrame(d1, index=model_name_list)
result_df.sort_values(by='f1 score', ascending=False, inplace=True)
result_df

In [ ]:
import pandas as pd

results_df = pd.DataFrame({
    'Model': model_name_list,
    'F1 Score': f1_score_list
})

results_df.sort_values(by='F1 Score', ascending=False)