In [5]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

In [6]:
df = pd.read_parquet('/Users/hapresent/Desktop/11_파이널프로젝트관련/open/train/8.성과정보/merged_data.parquet')

In [7]:
df1 = df.copy()

In [8]:
df1.columns

Index(['기준년월', 'ID', '증감율_이용건수_신용_전월', '증감율_이용건수_신판_전월', '증감율_이용건수_일시불_전월',
       '증감율_이용건수_할부_전월', '증감율_이용건수_CA_전월', '증감율_이용건수_체크_전월', '증감율_이용건수_카드론_전월',
       '증감율_이용금액_신용_전월', '증감율_이용금액_신판_전월', '증감율_이용금액_일시불_전월', '증감율_이용금액_할부_전월',
       '증감율_이용금액_CA_전월', '증감율_이용금액_체크_전월', '증감율_이용금액_카드론_전월', '증감율_이용건수_신용_분기',
       '증감율_이용건수_신판_분기', '증감율_이용건수_일시불_분기', '증감율_이용건수_할부_분기', '증감율_이용건수_CA_분기',
       '증감율_이용건수_체크_분기', '증감율_이용건수_카드론_분기', '증감율_이용금액_신용_분기', '증감율_이용금액_신판_분기',
       '증감율_이용금액_일시불_분기', '증감율_이용금액_할부_분기', '증감율_이용금액_CA_분기', '증감율_이용금액_체크_분기',
       '증감율_이용금액_카드론_분기', '잔액_신판평균한도소진율_r6m', '잔액_신판최대한도소진율_r6m',
       '잔액_신판평균한도소진율_r3m', '잔액_신판최대한도소진율_r3m', '잔액_신판ca평균한도소진율_r6m',
       '잔액_신판ca최대한도소진율_r6m', '잔액_신판ca평균한도소진율_r3m', '잔액_신판ca최대한도소진율_r3m',
       '변동률_일시불평잔', '변동률_RV일시불평잔', '변동률_할부평잔', '변동률_CA평잔', '변동률_RVCA평잔',
       '변동률_카드론평잔', '변동률_잔액_B1M', '변동률_잔액_일시불_B1M', '변동률_잔액_CA_B1M',
       '혜택수혜율_R3M', '혜택수혜율_B0M', 'Segment'],
      dtype='object')

In [9]:
#유의미 피처선택하기

selected_cols = ['ID','기준년월','증감율_이용건수_할부_전월' ,#'증감율_이용건수_할부_분기(이상치비율높음)'
                 '증감율_이용건수_CA_분기', '증감율_이용건수_체크_분기',
'증감율_이용금액_할부_전월', '증감율_이용금액_일시불_전월','잔액_신판ca최대한도소진율_r6m', '변동률_RV일시불평잔',#'변동률_할부평잔'제거하기(이상치비율높음),
'변동률_잔액_B1M','변동률_잔액_일시불_B1M', 
'혜택수혜율_R3M', 'Segment']

In [10]:
df_selected = df1[selected_cols]

In [11]:
df_selected

,ID,기준년월,증감율_이용건수_할부_전월,증감율_이용건수_CA_분기,증감율_이용건수_체크_분기,증감율_이용금액_할부_전월,증감율_이용금액_일시불_전월,잔액_신판ca최대한도소진율_r6m,변동률_RV일시불평잔,변동률_잔액_B1M,변동률_잔액_일시불_B1M,혜택수혜율_R3M,Segment
0,TRAIN_000000,201807,1.999996,0.0,-1.999996,1.999996,0.313300,0.849842,0.999998,0.261886,0.270752,1.044401,D
1,TRAIN_000001,201807,0.000000,0.0,0.000000,0.000000,-1.010817,0.851009,1.092698,-0.563388,-0.670348,0.000000,E
2,TRAIN_000002,201807,-1.999996,0.0,0.000000,-1.999996,0.289565,0.938161,1.006124,-0.046516,0.058114,0.524159,C
3,TRAIN_000003,201807,-1.999996,0.0,0.000000,-0.138126,0.276947,1.135424,0.999998,0.023821,0.258943,0.880925,D
4,TRAIN_000004,201807,0.000000,0.0,-0.404712,0.000000,0.000028,0.000000,0.999998,0.000000,0.000000,NaN,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...
399995,TRAIN_399995,201812,0.000000,0.0,-0.105145,0.000000,0.000027,0.032439,0.999998,0.000000,0.000000,NaN,E
399996,TRAIN_399996,201812,0.000000,0.0,0.000000,0.000000,0.207099,0.168081,0.999998,-0.203251,-0.159143,1.377071,D
399997,TRAIN_399997,201812,0.000000,0.0,0.000000,-1.999996,0.229573,0.190393,0.999998,0.027319,0.126581,0.000000,C
399998,TRAIN_399998,201812,0.000000,0.0,0.000000,0.000000,0.000034,0.012677,0.999998,0.000000,0.000000,NaN,E
399999,TRAIN_399999,201812,0.000000,0.0,0.000000,-0.137569,0.284271,0.053036,0.999998,-0.039845,-0.002659,0.000000,E

In [12]:
df_selected.to_csv('performance_selected_reflected_outliers_final_final_.csv', index=False)

| No. | 피처명                  | 이상치 개수   | 이상치 비율 |
| --- | -------------------- | -------- | ------ |
| 1   | ID                   | -        | -      |
| 2   | 기준년월                 | 0개       | 0.00%  |
| 3   | 증감율\_이용건수\_할부\_전월    | 212,791개 | 8.87%  |
| 4   | 증감율\_이용건수\_할부\_분기    | 621,641개 | 25.90% |
| 5   | 증감율\_이용건수\_CA\_분기    | 137,764개 | 5.74%  |
| 6   | 증감율\_이용건수\_체크\_분기    | 422,038개 | 17.58% |
| 7   | 증감율\_이용금액\_할부\_전월    | 344,918개 | 14.37% |
| 8   | 증감율\_이용금액\_일시불\_전월   | 176,961개 | 7.37%  |
| 9   | 잔액\_신판ca최대한도소진율\_r6m | 169,711개 | 7.07%  |
| 10  | 변동률\_RV일시불평잔         | 525,122개 | 21.88% |
| 11  | 변동률\_할부평잔            | 670,716개 | 27.95% |
| 12  | 변동률\_잔액\_B1M         | 257,848개 | 10.74% |
| 13  | 변동률\_잔액\_일시불\_B1M    | 337,652개 | 14.07% |
| 14  | 혜택수혜율\_R3M           | 136,437개 | 5.68%  |
| 15  | Segment              | -        | -      |